/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const ClothingItem = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Text,
  'createdAt' : IDL.Int,
  'pricePerItem' : IDL.Nat,
  'isActive' : IDL.Bool,
});
export const ShopStatus = IDL.Variant({
  'active' : IDL.Null,
  'pending' : IDL.Null,
  'rejected' : IDL.Null,
  'suspended' : IDL.Null,
});
export const Shop = IDL.Record({
  'id' : IDL.Nat,
  'serviceArea' : IDL.Nat,
  'status' : ShopStatus,
  'ownerName' : IDL.Text,
  'ownerId' : IDL.Principal,
  'createdAt' : IDL.Int,
  'workingHours' : IDL.Text,
  'address' : IDL.Text,
  'shopName' : IDL.Text,
  'mobile' : IDL.Text,
  'pricePerCloth' : IDL.Nat,
});
export const AdminStats = IDL.Record({
  'pendingOrders' : IDL.Nat,
  'totalShops' : IDL.Nat,
  'activeOrders' : IDL.Nat,
  'totalEarnings' : IDL.Nat,
  'totalOrdersToday' : IDL.Nat,
  'pendingShopApprovals' : IDL.Nat,
  'totalCustomers' : IDL.Nat,
});
export const Area = IDL.Record({
  'id' : IDL.Nat,
  'city' : IDL.Text,
  'name' : IDL.Text,
  'isActive' : IDL.Bool,
  'assignedShopIds' : IDL.Vec(IDL.Nat),
  'pantPrice' : IDL.Nat,
  'dressPrice' : IDL.Nat,
  'pincode' : IDL.Text,
  'shirtPrice' : IDL.Nat,
});
export const Broadcast = IDL.Record({
  'id' : IDL.Nat,
  'sentAt' : IDL.Int,
  'targetAudience' : IDL.Text,
  'message' : IDL.Text,
});
export const Complaint = IDL.Record({
  'id' : IDL.Nat,
  'status' : IDL.Text,
  'complaintType' : IDL.Text,
  'createdAt' : IDL.Int,
  'description' : IDL.Text,
  'orderId' : IDL.Nat,
  'customerId' : IDL.Principal,
});
export const OrderStatus = IDL.Variant({
  'cancelled' : IDL.Null,
  'pending' : IDL.Null,
  'pickedUp' : IDL.Null,
  'delivered' : IDL.Null,
  'accepted' : IDL.Null,
  'ironing' : IDL.Null,
});
export const Order = IDL.Record({
  'id' : IDL.Nat,
  'status' : OrderStatus,
  'paymentMethod' : IDL.Text,
  'shirts' : IDL.Nat,
  'clothingItems' : IDL.Vec(
    IDL.Record({ 'itemId' : IDL.Nat, 'quantity' : IDL.Nat })
  ),
  'dresses' : IDL.Nat,
  'createdAt' : IDL.Int,
  'partnerId' : IDL.Opt(IDL.Principal),
  'updatedAt' : IDL.Int,
  'totalAmount' : IDL.Nat,
  'address' : IDL.Text,
  'customerId' : IDL.Principal,
  'pants' : IDL.Nat,
});
export const User = IDL.Record({
  'balance' : IDL.Nat,
  'isBlocked' : IDL.Bool,
  'name' : IDL.Text,
  'completedOrders' : IDL.Nat,
  'totalEarnings' : IDL.Nat,
  'phone' : IDL.Text,
});
export const UserProfile = IDL.Record({
  'name' : IDL.Text,
  'phone' : IDL.Text,
});
export const Notification = IDL.Record({
  'id' : IDL.Nat,
  'userId' : IDL.Principal,
  'createdAt' : IDL.Int,
  'read' : IDL.Bool,
  'message' : IDL.Text,
});
export const ApprovalStatus = IDL.Variant({
  'pending' : IDL.Null,
  'approved' : IDL.Null,
  'rejected' : IDL.Null,
});
export const UserApprovalInfo = IDL.Record({
  'status' : ApprovalStatus,
  'principal' : IDL.Principal,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addArea' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [IDL.Nat], []),
  'addClothingItem' : IDL.Func([IDL.Text, IDL.Nat], [IDL.Nat], []),
  'approveShop' : IDL.Func([IDL.Nat], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'assignShopToArea' : IDL.Func([IDL.Nat, IDL.Nat], [], []),
  'blockUser' : IDL.Func([IDL.Principal], [], []),
  'claimAdminIfFirst' : IDL.Func([], [IDL.Bool], []),
  'deleteClothingItem' : IDL.Func([IDL.Nat], [], []),
  'deleteShop' : IDL.Func([IDL.Nat], [], []),
  'disableArea' : IDL.Func([IDL.Nat], [], []),
  'disableClothingItem' : IDL.Func([IDL.Nat], [], []),
  'enableArea' : IDL.Func([IDL.Nat], [], []),
  'enableClothingItem' : IDL.Func([IDL.Nat], [], []),
  'getActiveClothingItems' : IDL.Func([], [IDL.Vec(ClothingItem)], ['query']),
  'getActiveShops' : IDL.Func([], [IDL.Vec(Shop)], ['query']),
  'getAdminPrincipals' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
  'getAdminStats' : IDL.Func([], [AdminStats], ['query']),
  'getAllAreas' : IDL.Func([], [IDL.Vec(Area)], ['query']),
  'getAllBroadcasts' : IDL.Func([], [IDL.Vec(Broadcast)], ['query']),
  'getAllClothingItems' : IDL.Func([], [IDL.Vec(ClothingItem)], ['query']),
  'getAllComplaints' : IDL.Func([], [IDL.Vec(Complaint)], ['query']),
  'getAllOrders' : IDL.Func([], [IDL.Vec(Order)], ['query']),
  'getAllRegisteredUsers' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Principal, User))],
      ['query'],
    ),
  'getAllShops' : IDL.Func([], [IDL.Vec(Shop)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getMyOrders' : IDL.Func([], [IDL.Vec(Order)], ['query']),
  'getMyShop' : IDL.Func([], [IDL.Opt(Shop)], ['query']),
  'getOrder' : IDL.Func([IDL.Nat], [Order], ['query']),
  'getPricing' : IDL.Func(
      [],
      [
        IDL.Record({
          'pantPrice' : IDL.Nat,
          'dressPrice' : IDL.Nat,
          'shirtPrice' : IDL.Nat,
        }),
      ],
      ['query'],
    ),
  'getShopsByStatus' : IDL.Func([ShopStatus], [IDL.Vec(Shop)], ['query']),
  'getUser' : IDL.Func([IDL.Principal], [User], ['query']),
  'getUserNotifications' : IDL.Func([], [IDL.Vec(Notification)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'isCallerApproved' : IDL.Func([], [IDL.Bool], ['query']),
  'isUserBlocked' : IDL.Func([IDL.Principal], [IDL.Bool], ['query']),
  'listApprovals' : IDL.Func([], [IDL.Vec(UserApprovalInfo)], ['query']),
  'placeOrder' : IDL.Func(
      [
        IDL.Nat,
        IDL.Nat,
        IDL.Nat,
        IDL.Vec(IDL.Record({ 'itemId' : IDL.Nat, 'quantity' : IDL.Nat })),
        IDL.Text,
        IDL.Text,
      ],
      [IDL.Nat],
      [],
    ),
  'registerShop' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Nat, IDL.Nat, IDL.Text],
      [IDL.Nat],
      [],
    ),
  'registerUser' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'rejectShop' : IDL.Func([IDL.Nat], [], []),
  'requestApproval' : IDL.Func([], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'sendBroadcastNotification' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'setApproval' : IDL.Func([IDL.Principal, ApprovalStatus], [], []),
  'setAreaPrice' : IDL.Func([IDL.Nat, IDL.Nat, IDL.Nat, IDL.Nat], [], []),
  'setDressPrice' : IDL.Func([IDL.Nat], [], []),
  'setPantPrice' : IDL.Func([IDL.Nat], [], []),
  'setShirtPrice' : IDL.Func([IDL.Nat], [], []),
  'submitComplaint' : IDL.Func([IDL.Nat, IDL.Text, IDL.Text], [], []),
  'suspendShop' : IDL.Func([IDL.Nat], [], []),
  'unblockUser' : IDL.Func([IDL.Principal], [], []),
  'updateClothingItem' : IDL.Func([IDL.Nat, IDL.Text, IDL.Nat], [], []),
  'updateComplaintStatus' : IDL.Func([IDL.Nat, IDL.Text], [], []),
  'updateOrderStatus' : IDL.Func([IDL.Nat, OrderStatus], [], []),
  'whoAmI' : IDL.Func([], [IDL.Text], ['query']),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const ClothingItem = IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Text,
    'createdAt' : IDL.Int,
    'pricePerItem' : IDL.Nat,
    'isActive' : IDL.Bool,
  });
  const ShopStatus = IDL.Variant({
    'active' : IDL.Null,
    'pending' : IDL.Null,
    'rejected' : IDL.Null,
    'suspended' : IDL.Null,
  });
  const Shop = IDL.Record({
    'id' : IDL.Nat,
    'serviceArea' : IDL.Nat,
    'status' : ShopStatus,
    'ownerName' : IDL.Text,
    'ownerId' : IDL.Principal,
    'createdAt' : IDL.Int,
    'workingHours' : IDL.Text,
    'address' : IDL.Text,
    'shopName' : IDL.Text,
    'mobile' : IDL.Text,
    'pricePerCloth' : IDL.Nat,
  });
  const AdminStats = IDL.Record({
    'pendingOrders' : IDL.Nat,
    'totalShops' : IDL.Nat,
    'activeOrders' : IDL.Nat,
    'totalEarnings' : IDL.Nat,
    'totalOrdersToday' : IDL.Nat,
    'pendingShopApprovals' : IDL.Nat,
    'totalCustomers' : IDL.Nat,
  });
  const Area = IDL.Record({
    'id' : IDL.Nat,
    'city' : IDL.Text,
    'name' : IDL.Text,
    'isActive' : IDL.Bool,
    'assignedShopIds' : IDL.Vec(IDL.Nat),
    'pantPrice' : IDL.Nat,
    'dressPrice' : IDL.Nat,
    'pincode' : IDL.Text,
    'shirtPrice' : IDL.Nat,
  });
  const Broadcast = IDL.Record({
    'id' : IDL.Nat,
    'sentAt' : IDL.Int,
    'targetAudience' : IDL.Text,
    'message' : IDL.Text,
  });
  const Complaint = IDL.Record({
    'id' : IDL.Nat,
    'status' : IDL.Text,
    'complaintType' : IDL.Text,
    'createdAt' : IDL.Int,
    'description' : IDL.Text,
    'orderId' : IDL.Nat,
    'customerId' : IDL.Principal,
  });
  const OrderStatus = IDL.Variant({
    'cancelled' : IDL.Null,
    'pending' : IDL.Null,
    'pickedUp' : IDL.Null,
    'delivered' : IDL.Null,
    'accepted' : IDL.Null,
    'ironing' : IDL.Null,
  });
  const Order = IDL.Record({
    'id' : IDL.Nat,
    'status' : OrderStatus,
    'paymentMethod' : IDL.Text,
    'shirts' : IDL.Nat,
    'clothingItems' : IDL.Vec(
      IDL.Record({ 'itemId' : IDL.Nat, 'quantity' : IDL.Nat })
    ),
    'dresses' : IDL.Nat,
    'createdAt' : IDL.Int,
    'partnerId' : IDL.Opt(IDL.Principal),
    'updatedAt' : IDL.Int,
    'totalAmount' : IDL.Nat,
    'address' : IDL.Text,
    'customerId' : IDL.Principal,
    'pants' : IDL.Nat,
  });
  const User = IDL.Record({
    'balance' : IDL.Nat,
    'isBlocked' : IDL.Bool,
    'name' : IDL.Text,
    'completedOrders' : IDL.Nat,
    'totalEarnings' : IDL.Nat,
    'phone' : IDL.Text,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text, 'phone' : IDL.Text });
  const Notification = IDL.Record({
    'id' : IDL.Nat,
    'userId' : IDL.Principal,
    'createdAt' : IDL.Int,
    'read' : IDL.Bool,
    'message' : IDL.Text,
  });
  const ApprovalStatus = IDL.Variant({
    'pending' : IDL.Null,
    'approved' : IDL.Null,
    'rejected' : IDL.Null,
  });
  const UserApprovalInfo = IDL.Record({
    'status' : ApprovalStatus,
    'principal' : IDL.Principal,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addArea' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [IDL.Nat], []),
    'addClothingItem' : IDL.Func([IDL.Text, IDL.Nat], [IDL.Nat], []),
    'approveShop' : IDL.Func([IDL.Nat], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'assignShopToArea' : IDL.Func([IDL.Nat, IDL.Nat], [], []),
    'blockUser' : IDL.Func([IDL.Principal], [], []),
    'claimAdminIfFirst' : IDL.Func([], [IDL.Bool], []),
    'deleteClothingItem' : IDL.Func([IDL.Nat], [], []),
    'deleteShop' : IDL.Func([IDL.Nat], [], []),
    'disableArea' : IDL.Func([IDL.Nat], [], []),
    'disableClothingItem' : IDL.Func([IDL.Nat], [], []),
    'enableArea' : IDL.Func([IDL.Nat], [], []),
    'enableClothingItem' : IDL.Func([IDL.Nat], [], []),
    'getActiveClothingItems' : IDL.Func([], [IDL.Vec(ClothingItem)], ['query']),
    'getActiveShops' : IDL.Func([], [IDL.Vec(Shop)], ['query']),
    'getAdminPrincipals' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
    'getAdminStats' : IDL.Func([], [AdminStats], ['query']),
    'getAllAreas' : IDL.Func([], [IDL.Vec(Area)], ['query']),
    'getAllBroadcasts' : IDL.Func([], [IDL.Vec(Broadcast)], ['query']),
    'getAllClothingItems' : IDL.Func([], [IDL.Vec(ClothingItem)], ['query']),
    'getAllComplaints' : IDL.Func([], [IDL.Vec(Complaint)], ['query']),
    'getAllOrders' : IDL.Func([], [IDL.Vec(Order)], ['query']),
    'getAllRegisteredUsers' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Principal, User))],
        ['query'],
      ),
    'getAllShops' : IDL.Func([], [IDL.Vec(Shop)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getMyOrders' : IDL.Func([], [IDL.Vec(Order)], ['query']),
    'getMyShop' : IDL.Func([], [IDL.Opt(Shop)], ['query']),
    'getOrder' : IDL.Func([IDL.Nat], [Order], ['query']),
    'getPricing' : IDL.Func(
        [],
        [
          IDL.Record({
            'pantPrice' : IDL.Nat,
            'dressPrice' : IDL.Nat,
            'shirtPrice' : IDL.Nat,
          }),
        ],
        ['query'],
      ),
    'getShopsByStatus' : IDL.Func([ShopStatus], [IDL.Vec(Shop)], ['query']),
    'getUser' : IDL.Func([IDL.Principal], [User], ['query']),
    'getUserNotifications' : IDL.Func([], [IDL.Vec(Notification)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'isCallerApproved' : IDL.Func([], [IDL.Bool], ['query']),
    'isUserBlocked' : IDL.Func([IDL.Principal], [IDL.Bool], ['query']),
    'listApprovals' : IDL.Func([], [IDL.Vec(UserApprovalInfo)], ['query']),
    'placeOrder' : IDL.Func(
        [
          IDL.Nat,
          IDL.Nat,
          IDL.Nat,
          IDL.Vec(IDL.Record({ 'itemId' : IDL.Nat, 'quantity' : IDL.Nat })),
          IDL.Text,
          IDL.Text,
        ],
        [IDL.Nat],
        [],
      ),
    'registerShop' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Nat, IDL.Nat, IDL.Text],
        [IDL.Nat],
        [],
      ),
    'registerUser' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'rejectShop' : IDL.Func([IDL.Nat], [], []),
    'requestApproval' : IDL.Func([], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'sendBroadcastNotification' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'setApproval' : IDL.Func([IDL.Principal, ApprovalStatus], [], []),
    'setAreaPrice' : IDL.Func([IDL.Nat, IDL.Nat, IDL.Nat, IDL.Nat], [], []),
    'setDressPrice' : IDL.Func([IDL.Nat], [], []),
    'setPantPrice' : IDL.Func([IDL.Nat], [], []),
    'setShirtPrice' : IDL.Func([IDL.Nat], [], []),
    'submitComplaint' : IDL.Func([IDL.Nat, IDL.Text, IDL.Text], [], []),
    'suspendShop' : IDL.Func([IDL.Nat], [], []),
    'unblockUser' : IDL.Func([IDL.Principal], [], []),
    'updateClothingItem' : IDL.Func([IDL.Nat, IDL.Text, IDL.Nat], [], []),
    'updateComplaintStatus' : IDL.Func([IDL.Nat, IDL.Text], [], []),
    'updateOrderStatus' : IDL.Func([IDL.Nat, OrderStatus], [], []),
    'whoAmI' : IDL.Func([], [IDL.Text], ['query']),
  });
};

export const init = ({ IDL }) => { return []; };