/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AdminStats {
  'pendingOrders' : bigint,
  'totalShops' : bigint,
  'activeOrders' : bigint,
  'totalEarnings' : bigint,
  'totalOrdersToday' : bigint,
  'pendingShopApprovals' : bigint,
  'totalCustomers' : bigint,
}
export type ApprovalStatus = { 'pending' : null } |
  { 'approved' : null } |
  { 'rejected' : null };
export interface Area {
  'id' : bigint,
  'city' : string,
  'name' : string,
  'isActive' : boolean,
  'assignedShopIds' : Array<bigint>,
  'pantPrice' : bigint,
  'dressPrice' : bigint,
  'pincode' : string,
  'shirtPrice' : bigint,
}
export interface Broadcast {
  'id' : bigint,
  'sentAt' : bigint,
  'targetAudience' : string,
  'message' : string,
}
export interface ClothingItem {
  'id' : bigint,
  'name' : string,
  'createdAt' : bigint,
  'pricePerItem' : bigint,
  'isActive' : boolean,
}
export interface Complaint {
  'id' : bigint,
  'status' : string,
  'complaintType' : string,
  'createdAt' : bigint,
  'description' : string,
  'orderId' : bigint,
  'customerId' : Principal,
}
export interface Notification {
  'id' : bigint,
  'userId' : Principal,
  'createdAt' : bigint,
  'read' : boolean,
  'message' : string,
}
export interface Order {
  'id' : bigint,
  'status' : OrderStatus,
  'paymentMethod' : string,
  'shirts' : bigint,
  'clothingItems' : Array<{ 'itemId' : bigint, 'quantity' : bigint }>,
  'dresses' : bigint,
  'createdAt' : bigint,
  'partnerId' : [] | [Principal],
  'updatedAt' : bigint,
  'totalAmount' : bigint,
  'address' : string,
  'customerId' : Principal,
  'pants' : bigint,
}
export type OrderStatus = { 'cancelled' : null } |
  { 'pending' : null } |
  { 'pickedUp' : null } |
  { 'delivered' : null } |
  { 'accepted' : null } |
  { 'ironing' : null };
export interface Shop {
  'id' : bigint,
  'serviceArea' : bigint,
  'status' : ShopStatus,
  'ownerName' : string,
  'ownerId' : Principal,
  'createdAt' : bigint,
  'workingHours' : string,
  'address' : string,
  'shopName' : string,
  'mobile' : string,
  'pricePerCloth' : bigint,
}
export type ShopStatus = { 'active' : null } |
  { 'pending' : null } |
  { 'rejected' : null } |
  { 'suspended' : null };
export interface User {
  'balance' : bigint,
  'isBlocked' : boolean,
  'name' : string,
  'completedOrders' : bigint,
  'totalEarnings' : bigint,
  'phone' : string,
}
export interface UserApprovalInfo {
  'status' : ApprovalStatus,
  'principal' : Principal,
}
export interface UserProfile { 'name' : string, 'phone' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addArea' : ActorMethod<[string, string, string], bigint>,
  'addClothingItem' : ActorMethod<[string, bigint], bigint>,
  'approveShop' : ActorMethod<[bigint], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'assignShopToArea' : ActorMethod<[bigint, bigint], undefined>,
  'blockUser' : ActorMethod<[Principal], undefined>,
  'claimAdminIfFirst' : ActorMethod<[], boolean>,
  'deleteClothingItem' : ActorMethod<[bigint], undefined>,
  'deleteShop' : ActorMethod<[bigint], undefined>,
  'disableArea' : ActorMethod<[bigint], undefined>,
  'disableClothingItem' : ActorMethod<[bigint], undefined>,
  'enableArea' : ActorMethod<[bigint], undefined>,
  'enableClothingItem' : ActorMethod<[bigint], undefined>,
  'getActiveClothingItems' : ActorMethod<[], Array<ClothingItem>>,
  'getActiveShops' : ActorMethod<[], Array<Shop>>,
  'getAdminPrincipals' : ActorMethod<[], Array<string>>,
  'getAdminStats' : ActorMethod<[], AdminStats>,
  'getAllAreas' : ActorMethod<[], Array<Area>>,
  'getAllBroadcasts' : ActorMethod<[], Array<Broadcast>>,
  'getAllClothingItems' : ActorMethod<[], Array<ClothingItem>>,
  'getAllComplaints' : ActorMethod<[], Array<Complaint>>,
  'getAllOrders' : ActorMethod<[], Array<Order>>,
  'getAllRegisteredUsers' : ActorMethod<[], Array<[Principal, User]>>,
  'getAllShops' : ActorMethod<[], Array<Shop>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getMyOrders' : ActorMethod<[], Array<Order>>,
  'getMyShop' : ActorMethod<[], [] | [Shop]>,
  'getOrder' : ActorMethod<[bigint], Order>,
  'getPricing' : ActorMethod<
    [],
    { 'pantPrice' : bigint, 'dressPrice' : bigint, 'shirtPrice' : bigint }
  >,
  'getShopsByStatus' : ActorMethod<[ShopStatus], Array<Shop>>,
  'getUser' : ActorMethod<[Principal], User>,
  'getUserNotifications' : ActorMethod<[], Array<Notification>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'isCallerApproved' : ActorMethod<[], boolean>,
  'isUserBlocked' : ActorMethod<[Principal], boolean>,
  'listApprovals' : ActorMethod<[], Array<UserApprovalInfo>>,
  'placeOrder' : ActorMethod<
    [
      bigint,
      bigint,
      bigint,
      Array<{ 'itemId' : bigint, 'quantity' : bigint }>,
      string,
      string,
    ],
    bigint
  >,
  'registerShop' : ActorMethod<
    [string, string, string, string, bigint, bigint, string],
    bigint
  >,
  'registerUser' : ActorMethod<[string, string], undefined>,
  'rejectShop' : ActorMethod<[bigint], undefined>,
  'requestApproval' : ActorMethod<[], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'sendBroadcastNotification' : ActorMethod<[string, string], undefined>,
  'setApproval' : ActorMethod<[Principal, ApprovalStatus], undefined>,
  'setAreaPrice' : ActorMethod<[bigint, bigint, bigint, bigint], undefined>,
  'setDressPrice' : ActorMethod<[bigint], undefined>,
  'setPantPrice' : ActorMethod<[bigint], undefined>,
  'setShirtPrice' : ActorMethod<[bigint], undefined>,
  'submitComplaint' : ActorMethod<[bigint, string, string], undefined>,
  'suspendShop' : ActorMethod<[bigint], undefined>,
  'unblockUser' : ActorMethod<[Principal], undefined>,
  'updateClothingItem' : ActorMethod<[bigint, string, bigint], undefined>,
  'updateComplaintStatus' : ActorMethod<[bigint, string], undefined>,
  'updateOrderStatus' : ActorMethod<[bigint, OrderStatus], undefined>,
  'whoAmI' : ActorMethod<[], string>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];