/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface User {
    balance: bigint;
    isBlocked: boolean;
    name: string;
    completedOrders: bigint;
    totalEarnings: bigint;
    phone: string;
}
export interface ClothingItem {
    id: bigint;
    name: string;
    createdAt: bigint;
    pricePerItem: bigint;
    isActive: boolean;
}
export interface Order {
    id: bigint;
    status: OrderStatus;
    paymentMethod: string;
    shirts: bigint;
    clothingItems: Array<{
        itemId: bigint;
        quantity: bigint;
    }>;
    dresses: bigint;
    createdAt: bigint;
    partnerId?: Principal;
    updatedAt: bigint;
    totalAmount: bigint;
    address: string;
    customerId: Principal;
    pants: bigint;
}
export interface Broadcast {
    id: bigint;
    sentAt: bigint;
    targetAudience: string;
    message: string;
}
export interface UserApprovalInfo {
    status: ApprovalStatus;
    principal: Principal;
}
export interface AdminStats {
    pendingOrders: bigint;
    totalShops: bigint;
    activeOrders: bigint;
    totalEarnings: bigint;
    totalOrdersToday: bigint;
    pendingShopApprovals: bigint;
    totalCustomers: bigint;
}
export interface Area {
    id: bigint;
    city: string;
    name: string;
    isActive: boolean;
    assignedShopIds: Array<bigint>;
    pantPrice: bigint;
    dressPrice: bigint;
    pincode: string;
    shirtPrice: bigint;
}
export interface Notification {
    id: bigint;
    userId: Principal;
    createdAt: bigint;
    read: boolean;
    message: string;
}
export interface Complaint {
    id: bigint;
    status: string;
    complaintType: string;
    createdAt: bigint;
    description: string;
    orderId: bigint;
    customerId: Principal;
}
export interface Shop {
    id: bigint;
    serviceArea: bigint;
    status: ShopStatus;
    ownerName: string;
    ownerId: Principal;
    createdAt: bigint;
    workingHours: string;
    address: string;
    shopName: string;
    mobile: string;
    pricePerCloth: bigint;
}
export interface UserProfile {
    name: string;
    phone: string;
}
export enum ApprovalStatus {
    pending = "pending",
    approved = "approved",
    rejected = "rejected"
}
export enum OrderStatus {
    cancelled = "cancelled",
    pending = "pending",
    pickedUp = "pickedUp",
    delivered = "delivered",
    accepted = "accepted",
    ironing = "ironing"
}
export enum ShopStatus {
    active = "active",
    pending = "pending",
    rejected = "rejected",
    suspended = "suspended"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    addArea(name: string, city: string, pincode: string): Promise<bigint>;
    addClothingItem(name: string, pricePerItem: bigint): Promise<bigint>;
    approveShop(shopId: bigint): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    assignShopToArea(shopId: bigint, areaId: bigint): Promise<void>;
    blockUser(userId: Principal): Promise<void>;
    claimAdminIfFirst(): Promise<boolean>;
    deleteClothingItem(itemId: bigint): Promise<void>;
    deleteShop(shopId: bigint): Promise<void>;
    disableArea(areaId: bigint): Promise<void>;
    disableClothingItem(itemId: bigint): Promise<void>;
    enableArea(areaId: bigint): Promise<void>;
    enableClothingItem(itemId: bigint): Promise<void>;
    getActiveClothingItems(): Promise<Array<ClothingItem>>;
    getActiveShops(): Promise<Array<Shop>>;
    getAdminPrincipals(): Promise<Array<string>>;
    getAdminStats(): Promise<AdminStats>;
    getAllAreas(): Promise<Array<Area>>;
    getAllBroadcasts(): Promise<Array<Broadcast>>;
    getAllClothingItems(): Promise<Array<ClothingItem>>;
    getAllComplaints(): Promise<Array<Complaint>>;
    getAllOrders(): Promise<Array<Order>>;
    getAllRegisteredUsers(): Promise<Array<[Principal, User]>>;
    getAllShops(): Promise<Array<Shop>>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getMyOrders(): Promise<Array<Order>>;
    getMyShop(): Promise<Shop | null>;
    getOrder(orderId: bigint): Promise<Order>;
    getPricing(): Promise<{
        pantPrice: bigint;
        dressPrice: bigint;
        shirtPrice: bigint;
    }>;
    getShopsByStatus(status: ShopStatus): Promise<Array<Shop>>;
    getUser(userId: Principal): Promise<User>;
    getUserNotifications(): Promise<Array<Notification>>;
    getUserProfile(userId: Principal): Promise<UserProfile | null>;
    isCallerAdmin(): Promise<boolean>;
    isCallerApproved(): Promise<boolean>;
    isUserBlocked(userId: Principal): Promise<boolean>;
    listApprovals(): Promise<Array<UserApprovalInfo>>;
    placeOrder(shirts: bigint, pants: bigint, dresses: bigint, itemQuantities: Array<{
        itemId: bigint;
        quantity: bigint;
    }>, address: string, paymentMethod: string): Promise<bigint>;
    registerShop(ownerName: string, mobile: string, shopName: string, address: string, serviceArea: bigint, pricePerCloth: bigint, workingHours: string): Promise<bigint>;
    registerUser(name: string, phone: string): Promise<void>;
    rejectShop(shopId: bigint): Promise<void>;
    requestApproval(): Promise<void>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    sendBroadcastNotification(message: string, targetAudience: string): Promise<void>;
    setApproval(user: Principal, status: ApprovalStatus): Promise<void>;
    setAreaPrice(areaId: bigint, shirtPrice: bigint, pantPrice: bigint, dressPrice: bigint): Promise<void>;
    setDressPrice(price: bigint): Promise<void>;
    setPantPrice(price: bigint): Promise<void>;
    setShirtPrice(price: bigint): Promise<void>;
    submitComplaint(orderId: bigint, complaintType: string, description: string): Promise<void>;
    suspendShop(shopId: bigint): Promise<void>;
    unblockUser(userId: Principal): Promise<void>;
    updateClothingItem(itemId: bigint, name: string, pricePerItem: bigint): Promise<void>;
    updateComplaintStatus(complaintId: bigint, status: string): Promise<void>;
    updateOrderStatus(orderId: bigint, status: OrderStatus): Promise<void>;
    whoAmI(): Promise<string>;
}
import type { ApprovalStatus as _ApprovalStatus, Order as _Order, OrderStatus as _OrderStatus, Shop as _Shop, ShopStatus as _ShopStatus, UserApprovalInfo as _UserApprovalInfo, UserProfile as _UserProfile, UserRole as _UserRole } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async addArea(arg0: string, arg1: string, arg2: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.addArea(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addArea(arg0, arg1, arg2);
            return result;
        }
    }
    async addClothingItem(arg0: string, arg1: bigint): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.addClothingItem(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addClothingItem(arg0, arg1);
            return result;
        }
    }
    async approveShop(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.approveShop(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.approveShop(arg0);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async assignShopToArea(arg0: bigint, arg1: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignShopToArea(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignShopToArea(arg0, arg1);
            return result;
        }
    }
    async blockUser(arg0: Principal): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.blockUser(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.blockUser(arg0);
            return result;
        }
    }
    async claimAdminIfFirst(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.claimAdminIfFirst();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.claimAdminIfFirst();
            return result;
        }
    }
    async deleteClothingItem(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteClothingItem(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteClothingItem(arg0);
            return result;
        }
    }
    async deleteShop(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteShop(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteShop(arg0);
            return result;
        }
    }
    async disableArea(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.disableArea(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.disableArea(arg0);
            return result;
        }
    }
    async disableClothingItem(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.disableClothingItem(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.disableClothingItem(arg0);
            return result;
        }
    }
    async enableArea(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.enableArea(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.enableArea(arg0);
            return result;
        }
    }
    async enableClothingItem(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.enableClothingItem(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.enableClothingItem(arg0);
            return result;
        }
    }
    async getActiveClothingItems(): Promise<Array<ClothingItem>> {
        if (this.processError) {
            try {
                const result = await this.actor.getActiveClothingItems();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getActiveClothingItems();
            return result;
        }
    }
    async getActiveShops(): Promise<Array<Shop>> {
        if (this.processError) {
            try {
                const result = await this.actor.getActiveShops();
                return from_candid_vec_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getActiveShops();
            return from_candid_vec_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAdminPrincipals(): Promise<Array<string>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAdminPrincipals();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAdminPrincipals();
            return result;
        }
    }
    async getAdminStats(): Promise<AdminStats> {
        if (this.processError) {
            try {
                const result = await this.actor.getAdminStats();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAdminStats();
            return result;
        }
    }
    async getAllAreas(): Promise<Array<Area>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllAreas();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllAreas();
            return result;
        }
    }
    async getAllBroadcasts(): Promise<Array<Broadcast>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllBroadcasts();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllBroadcasts();
            return result;
        }
    }
    async getAllClothingItems(): Promise<Array<ClothingItem>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllClothingItems();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllClothingItems();
            return result;
        }
    }
    async getAllComplaints(): Promise<Array<Complaint>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllComplaints();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllComplaints();
            return result;
        }
    }
    async getAllOrders(): Promise<Array<Order>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllOrders();
                return from_candid_vec_n8(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllOrders();
            return from_candid_vec_n8(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllRegisteredUsers(): Promise<Array<[Principal, User]>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllRegisteredUsers();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllRegisteredUsers();
            return result;
        }
    }
    async getAllShops(): Promise<Array<Shop>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllShops();
                return from_candid_vec_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllShops();
            return from_candid_vec_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n14(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n14(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n15(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n15(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMyOrders(): Promise<Array<Order>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyOrders();
                return from_candid_vec_n8(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyOrders();
            return from_candid_vec_n8(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMyShop(): Promise<Shop | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyShop();
                return from_candid_opt_n17(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyShop();
            return from_candid_opt_n17(this._uploadFile, this._downloadFile, result);
        }
    }
    async getOrder(arg0: bigint): Promise<Order> {
        if (this.processError) {
            try {
                const result = await this.actor.getOrder(arg0);
                return from_candid_Order_n9(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getOrder(arg0);
            return from_candid_Order_n9(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPricing(): Promise<{
        pantPrice: bigint;
        dressPrice: bigint;
        shirtPrice: bigint;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.getPricing();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPricing();
            return result;
        }
    }
    async getShopsByStatus(arg0: ShopStatus): Promise<Array<Shop>> {
        if (this.processError) {
            try {
                const result = await this.actor.getShopsByStatus(to_candid_ShopStatus_n18(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getShopsByStatus(to_candid_ShopStatus_n18(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUser(arg0: Principal): Promise<User> {
        if (this.processError) {
            try {
                const result = await this.actor.getUser(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUser(arg0);
            return result;
        }
    }
    async getUserNotifications(): Promise<Array<Notification>> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserNotifications();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserNotifications();
            return result;
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n14(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n14(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async isCallerApproved(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerApproved();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerApproved();
            return result;
        }
    }
    async isUserBlocked(arg0: Principal): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isUserBlocked(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isUserBlocked(arg0);
            return result;
        }
    }
    async listApprovals(): Promise<Array<UserApprovalInfo>> {
        if (this.processError) {
            try {
                const result = await this.actor.listApprovals();
                return from_candid_vec_n20(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listApprovals();
            return from_candid_vec_n20(this._uploadFile, this._downloadFile, result);
        }
    }
    async placeOrder(arg0: bigint, arg1: bigint, arg2: bigint, arg3: Array<{
        itemId: bigint;
        quantity: bigint;
    }>, arg4: string, arg5: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.placeOrder(arg0, arg1, arg2, arg3, arg4, arg5);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.placeOrder(arg0, arg1, arg2, arg3, arg4, arg5);
            return result;
        }
    }
    async registerShop(arg0: string, arg1: string, arg2: string, arg3: string, arg4: bigint, arg5: bigint, arg6: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.registerShop(arg0, arg1, arg2, arg3, arg4, arg5, arg6);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.registerShop(arg0, arg1, arg2, arg3, arg4, arg5, arg6);
            return result;
        }
    }
    async registerUser(arg0: string, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.registerUser(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.registerUser(arg0, arg1);
            return result;
        }
    }
    async rejectShop(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.rejectShop(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.rejectShop(arg0);
            return result;
        }
    }
    async requestApproval(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.requestApproval();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.requestApproval();
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(arg0);
            return result;
        }
    }
    async sendBroadcastNotification(arg0: string, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.sendBroadcastNotification(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.sendBroadcastNotification(arg0, arg1);
            return result;
        }
    }
    async setApproval(arg0: Principal, arg1: ApprovalStatus): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setApproval(arg0, to_candid_ApprovalStatus_n25(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setApproval(arg0, to_candid_ApprovalStatus_n25(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async setAreaPrice(arg0: bigint, arg1: bigint, arg2: bigint, arg3: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setAreaPrice(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setAreaPrice(arg0, arg1, arg2, arg3);
            return result;
        }
    }
    async setDressPrice(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setDressPrice(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setDressPrice(arg0);
            return result;
        }
    }
    async setPantPrice(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setPantPrice(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setPantPrice(arg0);
            return result;
        }
    }
    async setShirtPrice(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setShirtPrice(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setShirtPrice(arg0);
            return result;
        }
    }
    async submitComplaint(arg0: bigint, arg1: string, arg2: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.submitComplaint(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitComplaint(arg0, arg1, arg2);
            return result;
        }
    }
    async suspendShop(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.suspendShop(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.suspendShop(arg0);
            return result;
        }
    }
    async unblockUser(arg0: Principal): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.unblockUser(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.unblockUser(arg0);
            return result;
        }
    }
    async updateClothingItem(arg0: bigint, arg1: string, arg2: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateClothingItem(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateClothingItem(arg0, arg1, arg2);
            return result;
        }
    }
    async updateComplaintStatus(arg0: bigint, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateComplaintStatus(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateComplaintStatus(arg0, arg1);
            return result;
        }
    }
    async updateOrderStatus(arg0: bigint, arg1: OrderStatus): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateOrderStatus(arg0, to_candid_OrderStatus_n27(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateOrderStatus(arg0, to_candid_OrderStatus_n27(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async whoAmI(): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.whoAmI();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.whoAmI();
            return result;
        }
    }
}
function from_candid_ApprovalStatus_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ApprovalStatus): ApprovalStatus {
    return from_candid_variant_n24(_uploadFile, _downloadFile, value);
}
function from_candid_OrderStatus_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _OrderStatus): OrderStatus {
    return from_candid_variant_n12(_uploadFile, _downloadFile, value);
}
function from_candid_Order_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Order): Order {
    return from_candid_record_n10(_uploadFile, _downloadFile, value);
}
function from_candid_ShopStatus_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ShopStatus): ShopStatus {
    return from_candid_variant_n7(_uploadFile, _downloadFile, value);
}
function from_candid_Shop_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Shop): Shop {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
function from_candid_UserApprovalInfo_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserApprovalInfo): UserApprovalInfo {
    return from_candid_record_n22(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n16(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [Principal]): Principal | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Shop]): Shop | null {
    return value.length === 0 ? null : from_candid_Shop_n4(_uploadFile, _downloadFile, value[0]);
}
function from_candid_record_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    status: _OrderStatus;
    paymentMethod: string;
    shirts: bigint;
    clothingItems: Array<{
        itemId: bigint;
        quantity: bigint;
    }>;
    dresses: bigint;
    createdAt: bigint;
    partnerId: [] | [Principal];
    updatedAt: bigint;
    totalAmount: bigint;
    address: string;
    customerId: Principal;
    pants: bigint;
}): {
    id: bigint;
    status: OrderStatus;
    paymentMethod: string;
    shirts: bigint;
    clothingItems: Array<{
        itemId: bigint;
        quantity: bigint;
    }>;
    dresses: bigint;
    createdAt: bigint;
    partnerId?: Principal;
    updatedAt: bigint;
    totalAmount: bigint;
    address: string;
    customerId: Principal;
    pants: bigint;
} {
    return {
        id: value.id,
        status: from_candid_OrderStatus_n11(_uploadFile, _downloadFile, value.status),
        paymentMethod: value.paymentMethod,
        shirts: value.shirts,
        clothingItems: value.clothingItems,
        dresses: value.dresses,
        createdAt: value.createdAt,
        partnerId: record_opt_to_undefined(from_candid_opt_n13(_uploadFile, _downloadFile, value.partnerId)),
        updatedAt: value.updatedAt,
        totalAmount: value.totalAmount,
        address: value.address,
        customerId: value.customerId,
        pants: value.pants
    };
}
function from_candid_record_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    status: _ApprovalStatus;
    principal: Principal;
}): {
    status: ApprovalStatus;
    principal: Principal;
} {
    return {
        status: from_candid_ApprovalStatus_n23(_uploadFile, _downloadFile, value.status),
        principal: value.principal
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    serviceArea: bigint;
    status: _ShopStatus;
    ownerName: string;
    ownerId: Principal;
    createdAt: bigint;
    workingHours: string;
    address: string;
    shopName: string;
    mobile: string;
    pricePerCloth: bigint;
}): {
    id: bigint;
    serviceArea: bigint;
    status: ShopStatus;
    ownerName: string;
    ownerId: Principal;
    createdAt: bigint;
    workingHours: string;
    address: string;
    shopName: string;
    mobile: string;
    pricePerCloth: bigint;
} {
    return {
        id: value.id,
        serviceArea: value.serviceArea,
        status: from_candid_ShopStatus_n6(_uploadFile, _downloadFile, value.status),
        ownerName: value.ownerName,
        ownerId: value.ownerId,
        createdAt: value.createdAt,
        workingHours: value.workingHours,
        address: value.address,
        shopName: value.shopName,
        mobile: value.mobile,
        pricePerCloth: value.pricePerCloth
    };
}
function from_candid_variant_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    cancelled: null;
} | {
    pending: null;
} | {
    pickedUp: null;
} | {
    delivered: null;
} | {
    accepted: null;
} | {
    ironing: null;
}): OrderStatus {
    return "cancelled" in value ? OrderStatus.cancelled : "pending" in value ? OrderStatus.pending : "pickedUp" in value ? OrderStatus.pickedUp : "delivered" in value ? OrderStatus.delivered : "accepted" in value ? OrderStatus.accepted : "ironing" in value ? OrderStatus.ironing : value;
}
function from_candid_variant_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_variant_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    pending: null;
} | {
    approved: null;
} | {
    rejected: null;
}): ApprovalStatus {
    return "pending" in value ? ApprovalStatus.pending : "approved" in value ? ApprovalStatus.approved : "rejected" in value ? ApprovalStatus.rejected : value;
}
function from_candid_variant_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    active: null;
} | {
    pending: null;
} | {
    rejected: null;
} | {
    suspended: null;
}): ShopStatus {
    return "active" in value ? ShopStatus.active : "pending" in value ? ShopStatus.pending : "rejected" in value ? ShopStatus.rejected : "suspended" in value ? ShopStatus.suspended : value;
}
function from_candid_vec_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_UserApprovalInfo>): Array<UserApprovalInfo> {
    return value.map((x)=>from_candid_UserApprovalInfo_n21(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Shop>): Array<Shop> {
    return value.map((x)=>from_candid_Shop_n4(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Order>): Array<Order> {
    return value.map((x)=>from_candid_Order_n9(_uploadFile, _downloadFile, x));
}
function to_candid_ApprovalStatus_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ApprovalStatus): _ApprovalStatus {
    return to_candid_variant_n26(_uploadFile, _downloadFile, value);
}
function to_candid_OrderStatus_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: OrderStatus): _OrderStatus {
    return to_candid_variant_n28(_uploadFile, _downloadFile, value);
}
function to_candid_ShopStatus_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ShopStatus): _ShopStatus {
    return to_candid_variant_n19(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function to_candid_variant_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ShopStatus): {
    active: null;
} | {
    pending: null;
} | {
    rejected: null;
} | {
    suspended: null;
} {
    return value == ShopStatus.active ? {
        active: null
    } : value == ShopStatus.pending ? {
        pending: null
    } : value == ShopStatus.rejected ? {
        rejected: null
    } : value == ShopStatus.suspended ? {
        suspended: null
    } : value;
}
function to_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_variant_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ApprovalStatus): {
    pending: null;
} | {
    approved: null;
} | {
    rejected: null;
} {
    return value == ApprovalStatus.pending ? {
        pending: null
    } : value == ApprovalStatus.approved ? {
        approved: null
    } : value == ApprovalStatus.rejected ? {
        rejected: null
    } : value;
}
function to_candid_variant_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: OrderStatus): {
    cancelled: null;
} | {
    pending: null;
} | {
    pickedUp: null;
} | {
    delivered: null;
} | {
    accepted: null;
} | {
    ironing: null;
} {
    return value == OrderStatus.cancelled ? {
        cancelled: null
    } : value == OrderStatus.pending ? {
        pending: null
    } : value == OrderStatus.pickedUp ? {
        pickedUp: null
    } : value == OrderStatus.delivered ? {
        delivered: null
    } : value == OrderStatus.accepted ? {
        accepted: null
    } : value == OrderStatus.ironing ? {
        ironing: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
